version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bearatlas-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bearatlas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: bearatlas-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  typesense:
    image: typesense/typesense:0.25.2
    container_name: bearatlas-typesense
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY:-changeme}
    command: [
      "--data-dir", "/data",
      "--api-key", "${TYPESENSE_API_KEY:-changeme}",
      "--listen-port", "8108",
      "--enable-cors"
    ]
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8108/health"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  pgdata:
  typesense-data:
